baseURL: 'https://guoqiao.me'
title: "guoqiao's personal website"
theme: 'noteworthy'
languageCode: 'en-us'

enableRobotsTXT: true
paginate: 10
summaryLength: 20
publishDir: 'docs'

params:
  twitter: https://twitter.com/guoqiao
  github: https://github.com/guoqiao
